---
title: "BC-Maps"
author: "Anna Talucci"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Overview



# Packages
```{r}
  library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
  library(sf)
  library(ggmap) # devtools::install_github("dkahle/ggmap")
library(ggrepel)

library(raster)
library(rgdal)
library(rasterVis)
library(RColorBrewer)
library(cowplot)
library(ggspatial)
library(maps)
```


```{r}
ne1 <- 
  raster("../NE1/NE1_HR_LC_SR_W_DR.tif")

ne1
```

xmin: 273544 ymin: 369009.5 xmax: 1870570 ymax: 1735691
```{r}
plot(ne1)
```



```{r}
fire1 <- st_read(
  "../shapefiles/ch_R10070_2014.shp")
```

```{r}
fire2 <- st_read(
  "../shapefiles/en_R10171_2012.shp")
```

```{r}
fire3 <- st_read(
  "../shapefiles/tw_R10252_2013.shp")
```

```{r}
all_fires= st_read("../shapefiles/perimeter_merge.shp")
```

```{r}

(insetrect <- data.frame(xmin = 985362, xmax = 1069051,
    ymin = 894097.7, ymax = 939814.2))
```


```{r}
str(all_fires)
```

```{r}
bc = st_read("../shapefiles/province_bc_alber.shp")
```

```{r}
lakes = st_read("../shapefiles/Lakes_select_fire.shp")
```

```{r}
parks = st_read("../shapefiles/tweed-entiako_singlepoly.shp")
```

```{r}
city = st_read("../shapefiles/BC_Vancouver_PrinceGeorge.shp")
```

```{r}
str(city)
```

```{r}
labs <- tibble(
  long = c(-123.1207, -122.7497),
  lat = c(49.2827, 53.9171),
  names = c("Vancouver", "Prince George")) 
```

```{r}
linecolors <- c("#714C02", "#01587A", "#024E37")
fillcolors <- c("#9D6C06", "#077DAA", "#026D4E")

ggplot() + 
  geom_sf(data = bc, fill = NA, color = "black") +
  geom_point(data = all_fires, aes(x = lon, y= lat), position=position_jitter(h=0.1, w=0.1),
             shape = 21, alpha = 0.5, size = 10) +
    scale_color_manual(values=linecolors) +
  scale_fill_manual(values=fillcolors) +

  ggtitle("Fire perimeters for study area") + 
  coord_sf()
```

```{r}
ggplot() + 
  geom_sf(data = bc, fill = "gray75", color = "black") +
  geom_point(data = city, aes(x = lon, y= lat), shape = 24, size = 2, color = "red", fill = "red") +
  geom_label_repel(data = city, aes(x = lon, y= lat, label = c("Prince George", "Vancouver")), vjust = "top", hjust = "left", color = "black") +
  geom_point(data = fire1, aes(x = lon, y= lat), shape =21, alpha = 0.5, size = 3, color = "#714C02", fill = "#9D6C06", position=position_jitter(h=50, w=50)) +
  geom_point(data = fire2, aes(x = lon, y= lat), shape =21, alpha = 0.5, size = 3, color = "#024E37", fill = "#026D4E", position=position_jitter(h=-10, w=-10)) +
  geom_point(data = fire3, aes(x = lon, y= lat), shape =21, alpha = 0.5, size = 2, color = "#01587A", fill = "#077DAA") +
  xlab("")+ylab("")+
  coord_sf()
```


```{r}
ggplot() + 
  geom_sf(data = bc, fill = "gray75", color = "black") +
  geom_point(data = fire1, aes(x = lon, y= lat), shape =21, alpha = 0.5, size = 3, color = "#714C02", fill = "#9D6C06", position=position_jitter(h=50, w=50)) +
  geom_point(data = fire2, aes(x = lon, y= lat), shape =21, alpha = 0.5, size = 3, color = "#024E37", fill = "#026D4E", position=position_jitter(h=-10, w=-10)) +
  geom_point(data = fire3, aes(x = lon, y= lat), shape =21, alpha = 0.5, size = 2, color = "#01587A", fill = "#077DAA") +
  xlab("")+ylab("")+
  coord_sf() +
   
  # add a bounding box so that will border the inset
  theme(panel.background = element_rect(colour = "black", 
                                        size = 0.5))


```
```{r}
map_bc = ggplot() + 
  geom_sf(data = bc, fill = "#E8E8E8", color = "black") +
  geom_point(data = fire1, aes(x = lon, y= lat), shape =21, size = 3, color = "#b82b2b", fill = "#b82b2b", position=position_jitter(h=50, w=50)) +
  geom_point(data = fire2, aes(x = lon, y= lat), shape =21, size = 3, color = "#b82b2b", fill = "#b82b2b", position=position_jitter(h=-10, w=-10)) +
  geom_point(data = fire3, aes(x = lon, y= lat), shape =21, size = 2, color = "#b82b2b", fill = "#b82b2b") +
  xlab("")+ylab("")+
  coord_sf() +
   theme_void() +
  # add a bounding box so that will border the inset
  theme(panel.background = element_rect(colour = "black", fill = "white", size = 0.5))


map_bc
```


```{r}
map_bc2 = ggplot() + 
  geom_sf(data = bc, fill = "#E8E8E8", color = "black") +
  geom_rect(data = insetrect, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "#000080", size = 1.5, linetype = 1) +
  xlab("")+ylab("")+
  coord_sf() +
   theme_void() +
  # add a bounding box so that will border the inset
  theme(panel.background = element_rect(colour = "black", fill = "white", size = 0.5))


map_bc2
```


```{r}
ggplot() + 
  geom_sf(data = bc, fill = "#E8E8E8", color = "black", legend.outside = TRUE) 
```


```{r}
ggplot() + 
  geom_sf(data = bc, fill = "#E8E8E8", color = "black") +
  geom_sf(data = fire1, fill = NA, color = "#b82b2b", size = 1, show.legend = "line") +
  geom_sf(data = fire2, fill = NA, color = "#b06f0c", size = 1) +
  geom_sf(data = fire3, fill = NA, color = "#dd7116", size = 1) +
  xlab("")+ylab("")+
  coord_sf() +
  scale_colour_manual(values = c("#b82b2b", "#b06f0c", "#dd7116"),
                      guide = guide_legend(override.aes = list(linetype = c("blank", "solid")))) +

  # add a bounding box so that will border the inset
  theme(panel.background = element_rect(colour = "black", fill = "white", size = 0.5)) 



```


```{r}
 ggplot() + 
  geom_sf(data = bc, fill = "#E8E8E8", color = "black") +
  geom_point(data = fire1, aes(x = lon, y= lat), shape =21, size = 3, color = "#b82b2b", fill = "#b82b2b", position=position_jitter(h=50, w=50)) +
  geom_point(data = fire2, aes(x = lon, y= lat), shape =21, size = 3, color = "#b82b2b", fill = "#b82b2b", position=position_jitter(h=-10, w=-10)) +
  geom_point(data = fire3, aes(x = lon, y= lat), shape =21, size = 2, color = "#b82b2b", fill = "#b82b2b") +
  xlab("")+ylab("")+
  coord_sf() +
   theme_light() +
  # add a bounding box so that will border the inset
  theme(panel.background = element_rect(colour = "black", 
                                        size = 0.5))

```
 xmin: 985362 ymin: 894097.7 xmax: 1069051 ymax: 939814.2
  xmin: 999314.8 ymin: 894097.7 xmax: 1069051 ymax: 939814.2
```{r}
ggplot() +
  geom_sf(data = bc, fill = "#cfcfc4", color = "#cfcfc4") +
    geom_sf(data = parks, fill = "#56887d", color = "#56887d") +
    geom_sf(data = lakes, fill = "#56a0d3", color = "#56a0d3") +
  geom_sf(data = fire1, fill = NA, color = "brown") +
  geom_sf(data = fire2, fill = NA, color = "yellow") +
  geom_sf(data = fire3, fill = NA, color = "black") +
  coord_sf(crs = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", xlim = c(985362, 1069051), ylim = c(894097.7, 939814.2), expand = FALSE) 
```

```{r}
ggplot() +
  annotation_map_tile(type = "osm") +
  geom_sf(data = fire1, fill = NA, color = "#F6CF65", size = 2) +
  geom_sf(data = fire2, fill = NA, color = "#D5D8DB", size = 2) +
  geom_sf(data = fire3, fill = NA, color = "#FFF2AF", size = 2) +
  coord_sf(crs = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", xlim = c(985362, 1069051), ylim = c(894097.7, 939814.2), expand = FALSE) 
```

```{r}
ggplot() +
  geom_sf(data = bc, fill = "#E8E8E8", color = "#E8E8E8") +
    geom_sf(data = parks, fill = "#C3ECB2", color = "#C3ECB2") +
    geom_sf(data = lakes, fill = "#AADAFF", color = "#AADAFF") +
  geom_sf(data = fire1, fill = NA, color = "#F6CF65", size = 2) +
  geom_sf(data = fire2, fill = NA, color = "#D5D8DB", size = 2) +
  geom_sf(data = fire3, fill = NA, color = "#FFF2AF", size = 2) +
  scale_color_identity(name = "Map",
                          breaks = c("#E8E8E8", "#C3ECB2", "#AADAFF", "#F6CF65", "#D5D8DB", "#FFF2AF"),
                          labels = c("BC", "Parks", "lakes", "Fire1", "Fire2", "Fire3"),
                          guide = "legend") +
  coord_sf(crs = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", xlim = c(985362, 1069051), ylim = c(894097.7, 939814.2), expand = FALSE) 
```
xlim = c(985362, 1069051), ylim = c(894097.7, 939814.2),

## Manuscript

```{r}
map_legend = ggplot() +
  geom_sf(data = bc, aes(fill = "BC", color = "BC")) +
    geom_sf(data = parks, aes(fill = "Parks", color = "Parks"), show.legend = TRUE) +
    geom_sf(data = lakes, aes(fill = "Lakes", color = "Lakes"), show.legend = TRUE, key_glyph = draw_key_rect) +
  geom_sf(data = fire1, fill = NA, aes(color = "Fire1"), size = 1, show.legend = TRUE, key_glyph = draw_key_rect) +
  geom_sf(data = fire2, fill = NA, aes(color = "Fire2"), size = 1, show.legend = TRUE) +
  geom_sf(data = fire3, fill = NA, aes(color = "Fire3"), size = 1, show.legend = TRUE) +
  scale_color_manual(values = c("BC" = "#E8E8E8", "Parks" = "#C3ECB2", "Lakes" = "#AADAFF", "Fire1" = "#b82b2b", "Fire2" = "#b06f0c", "Fire3" =  "#dd7116"), 
                       labels = c("British Columbia", "Chelaslie fire", "Entiako fire", "Tweedsmuir fire", "Lakes", "Provincial parks"),
                       name = "Legend") +
  scale_fill_manual(values = c("BC" = "#E8E8E8", "Parks" = "#C3ECB2", "Lakes" = "#AADAFF", "Fire1" = NA, "Fire2" = NA, "Fire3" =  NA),
                    guide=FALSE) +
  coord_sf(crs = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", xlim = c(983000, 1071000), ylim = c(892000, 941000), expand = FALSE)  + 
      annotation_scale(location = "br", width_hint = 0.25, text_size = 12, text_face = NULL, text_family = "serif", text_col = "black") +
    annotation_north_arrow(location = "tl", which_north = "true", 
        pad_x = unit(0.1, "in"), pad_y = unit(0.1, "in"),
        style = north_arrow_nautical(line_width = 1, line_col = "black", fill = c("black", "white"), text_size = 10, text_face = NULL, text_family = "serif", text_col = "black", text_angle = 0)) +
  theme(axis.text.x = element_text(face = "plain", color = "black", size = 12),
        axis.text.y = element_text(face = "plain", color = "black", size = 12),
        legend.position= c(0.88, 0.35),
        legend.key = element_rect(fill = "white")) 


map_legend
```

Colors:
-- gray green #75816B
-- Silver #C0C0C0
-- light slate #778899
-- Tomato #ff6347
-- Gray #7E7E7E
-- dark slate #3F4354

```{r}
map_legend2 = ggplot() +
  geom_sf(data = bc, aes(fill = "BC", color = "BC")) +
    geom_sf(data = parks, aes(fill = "Parks", color = "Parks"), show.legend = TRUE) +
    geom_sf(data = lakes, aes(fill = "Lakes", color = "Lakes"), show.legend = TRUE, key_glyph = draw_key_rect) +
  geom_sf(data = fire1, fill = NA, aes(color = "Fire1"), size = 1, show.legend = TRUE, key_glyph = draw_key_rect) +
  geom_sf(data = fire2, fill = NA, aes(color = "Fire2"), size = 1, show.legend = TRUE) +
  geom_sf(data = fire3, fill = NA, aes(color = "Fire3"), size = 1, show.legend = TRUE) +
  scale_color_manual(values = c("BC" = "#7E7E7E", "Parks" = "#75816B", "Lakes" = "#AADAFF", "Fire1" = "#fee08b", "Fire2" = "#ff6347", "Fire3" ="#fdae61" ), 
                       labels = c("British Columbia", "Chelaslie fire", "Entiako fire", "Tweedsmuir fire", "Lakes", "Provincial parks"),
                       name = "") +
  scale_fill_manual(values = c("BC" = "#7E7E7E", "Parks" = "#75816B", "Lakes" = "#AADAFF", "Fire1" = NA, "Fire2" = NA, "Fire3" =  NA),
                    guide=FALSE) +
  coord_sf(crs = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", xlim = c(983000, 1071000), ylim = c(892000, 941000), expand = FALSE)  + 
      annotation_scale(location = "br", width_hint = 0.25, text_size = 12, text_face = NULL, text_family = "serif", text_col = "black") +
    annotation_north_arrow(location = "br", which_north = "true", 
        pad_x = unit(0.4, "in"), pad_y = unit(0.5, "in"),
        style = north_arrow_nautical(line_width = 1, line_col = "black", fill = c("black", "white"), text_size = 10, text_face = NULL, text_family = "serif", text_col = "black", text_angle = 0)) +
  theme(axis.text.x = element_text(face = "plain", color = "black", size = 10),
        axis.text.y = element_text(face = "plain", color = "black", size = 10),
        legend.position= "bottom",
        legend.key = element_rect(fill = "white")) 


map_legend2
```

### Combine with inset map
```{r fig.height=4, fig.width=6}

fig_manuscript2 = ggdraw() +
   draw_plot(map_legend2) +
  draw_plot(map_bc2, x = 0.12, y = 0.32, width = .25, height = .25) 
 

fig_manuscript2


```

```{r}
ggsave("../figures/bc_map_manuscript.png", plot = fig_manuscript2, width = 6, height = 4, dpi = 600)
```

## Poster
```{r}
map_fires = ggplot() +
  geom_sf(data = bc, fill = "#E8E8E8", color = "#E8E8E8") +
    geom_sf(data = parks, fill = "#C3ECB2", color = "#C3ECB2") +
    geom_sf(data = lakes, fill = "#AADAFF", color = "#AADAFF") +
  geom_sf(data = fire1, fill = NA, color = "#b82b2b", size = 1) +
  geom_sf(data = fire2, fill = NA, color = "#b06f0c", size = 1) +
  geom_sf(data = fire3, fill = NA, color = "#dd7116", size = 1) +
  coord_sf(crs = "+proj=aea +lat_1=50 +lat_2=58.5 +lat_0=45 +lon_0=-126 +x_0=1000000 +y_0=0 +datum=NAD83 +units=m +no_defs", xlim = c(983000, 1071000), ylim = c(892000, 941000), expand = FALSE)  + 
      annotation_scale(location = "br", width_hint = 0.25, text_size = 12, text_face = NULL, text_family = "serif", text_col = "black") +
    annotation_north_arrow(location = "br", which_north = "true", 
        pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
        style = north_arrow_nautical(line_width = 1, line_col = "black", fill = c("black", "white"), text_size = 10, text_face = NULL, text_family = "serif", text_col = "black", text_angle = 0)) +
  theme(axis.text.x = element_text(face = "plain", color = "black", size = 12),
        axis.text.y = element_text(face = "plain", color = "black", size = 12)) 


map_fires
```




